apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-relou
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /messageepsi
        backend:
          serviceName: dockettestapi
          servicePort: 3000